baseURL = 'https://aaronsaray.com/'
languageCode = 'en-us'
title = 'Milwaukee Web Developer, PHP and Laravel Programmer, Consultant'
theme = 'aaronsaray'
rssLimit = 10
copyright = 'This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.'

[taxonomies]
  tag = 'tag'

[permalinks]
  blog = '/:year/:filename/'

[outputs]
  home = ['HTML']

[markup]
  [markup.highlight]
    noClasses = false

[menu]
[[menu.main]]
  name = 'Home'
  identifier = 'home'
  url = '/'
  weight = 10
[[menu.main]]
  name = 'CV'
  identifier = 'cv'
  pageref = 'cv'
  weight = 20
[[menu.main]]
  name = 'Blog'
  pageref = 'blog'
  weight = 30
[[menu.main]]
  name = 'Contact'
  pageref = 'contact'
  weight = 40

[Params]
  description = 'Open Source Consultant specializing in building effective software for startups and SMBs.'