#!/bin/bash

docker run -it --rm --mount type=bind,source="$(pwd)",target=/srv/jekyll,consistency=delegated --mount type=bind,source="$(pwd)"/vendor-bundle,target=/usr/local/bundle,consistency=delegated --publish 4000:4000 jekyll/jekyll:3.8.6 jekyll "$@"