[build]
  base = ""
  publish = "public/"
  command = "npm --prefix=./themes/aaronsaray install && hugo"

[build.environment]
  HUGO_VERSION = "0.124.1"

[[redirects]]
  from = "https://aaronsaraycom.netlify.app"
  to = "https://aaronsaray.com"
  status = 301
  force = true

[[redirects]]
  from = "/book"
  to = "https://www.amazon.com/Professional-Design-Patterns-Aaron-Saray/dp/0470496703/"

[[redirects]]
  from = "/resume"
  to = "/cv"

[[redirects]]
  from = "/feed.xml"
  to = "/blog/index.xml"
